"""Email notification service using Resend.

Provides digest email generation for scrape job completions.
Disabled when RESEND_API_KEY is not configured — silently logs and returns.
"""

import logging
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# HTML email templates
# ---------------------------------------------------------------------------
DIGEST_EMAIL_HTML = """\
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0; padding:0; background-color:#f4f5f7; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f5f7; padding:32px 16px;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff; border-radius:12px; overflow:hidden; box-shadow:0 1px 3px rgba(0,0,0,0.1);">
          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#6366f1,#8b5cf6); padding:32px 32px 24px;">
              <h1 style="margin:0; color:#ffffff; font-size:24px; font-weight:700;">
                LeadForge Scrape Report
              </h1>
              <p style="margin:8px 0 0; color:rgba(255,255,255,0.85); font-size:14px;">
                {source_name} &middot; {platform}
              </p>
            </td>
          </tr>

          <!-- Summary Stats -->
          <tr>
            <td style="padding:24px 32px 0;">
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td style="text-align:center; padding:16px; background-color:#f8fafc; border-radius:8px;">
                    <p style="margin:0; font-size:28px; font-weight:700; color:#6366f1;">{leads_found}</p>
                    <p style="margin:4px 0 0; font-size:12px; color:#64748b;">Total Leads</p>
                  </td>
                  <td style="width:12px;"></td>
                  <td style="text-align:center; padding:16px; background-color:#f0fdf4; border-radius:8px;">
                    <p style="margin:0; font-size:28px; font-weight:700; color:#16a34a;">{high_priority}</p>
                    <p style="margin:4px 0 0; font-size:12px; color:#64748b;">High Priority (75+)</p>
                  </td>
                  <td style="width:12px;"></td>
                  <td style="text-align:center; padding:16px; background-color:#fefce8; border-radius:8px;">
                    <p style="margin:0; font-size:28px; font-weight:700; color:#ca8a04;">{top_count}</p>
                    <p style="margin:4px 0 0; font-size:12px; color:#64748b;">Top Matches</p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Top Leads Table -->
          {top_leads_section}

          <!-- Footer -->
          <tr>
            <td style="padding:24px 32px 32px; border-top:1px solid #e2e8f0;">
              <p style="margin:0; font-size:12px; color:#94a3b8;">
                Generated by LeadForge on {timestamp} (UTC)
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
"""

TOP_LEADS_ROW = """\
<tr>
  <td style="padding:12px 16px; border-bottom:1px solid #f1f5f9;">
    <p style="margin:0 0 4px; font-size:14px; font-weight:600; color:#1e293b;">
      {title}
    </p>
    <p style="margin:0 0 2px; font-size:12px; color:#64748b;">
      {company} &middot; {location}
    </p>
    <p style="margin:0; font-size:12px; color:#6366f1; font-weight:600;">
      Score: {score}/100
    </p>
  </td>
</tr>
"""

TOP_LEADS_SECTION = """\
<tr>
  <td style="padding:24px 32px 0;">
    <h2 style="margin:0 0 16px; font-size:16px; font-weight:600; color:#334155;">
      Top Leads
    </h2>
    <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f8fafc; border-radius:8px; overflow:hidden;">
      <tr>
        <td style="padding:8px 16px; background-color:#eef2ff; font-size:11px; font-weight:600; color:#4f46e5; text-transform:uppercase; letter-spacing:0.5px;">
          Best Matching Job Listings
        </td>
      </tr>
      {rows}
    </table>
  </td>
</tr>
"""


class EmailService:
    """Email notification service powered by Resend.

    Automatically disabled when ``RESEND_API_KEY`` is not set. All
    methods are safe to call regardless of configuration — failures
    are logged and never propagated.
    """

    def __init__(self) -> None:
        self._client: Any = None
        self._enabled = False
        self._from_address: str = ""

        self._init_client()

    def _init_client(self) -> None:
        """Lazily initialize the Resend client."""
        try:
            from app.config import settings

            api_key = getattr(settings, "RESEND_API_KEY", "")
            if not api_key:
                logger.info("RESEND_API_KEY not set — email notifications disabled")
                return

            import resend

            resend.api_key = api_key
            self._client = resend
            self._from_address = getattr(
                settings, "EMAIL_FROM_ADDRESS", "LeadForge <noreply@leadforge.dev>"
            )
            self._enabled = True
            logger.info("Email service initialized with Resend")

        except ImportError:
            logger.warning(
                "resend package not installed — email notifications disabled. "
                "Install with: pip install resend"
            )

    @property
    def is_enabled(self) -> bool:
        """Whether the email service is configured and active."""
        return self._enabled

    async def send_digest_email(
        self,
        to_email: str,
        subject: str,
        scrape_results: dict,
    ) -> bool:
        """Send a digest email summarizing a scrape job.

        Parameters
        ----------
        to_email:
            Recipient email address.
        subject:
            Email subject line.
        scrape_results:
            Dict with keys: source_name, platform, leads_found,
            high_priority_count, top_leads (list of dicts with
            title, company, location, score).

        Returns
        -------
        bool
            ``True`` if the email was sent successfully, ``False`` otherwise.
            Always returns ``False`` if the service is not enabled.
        """
        if not self._enabled:
            logger.debug("Email service disabled — skipping digest")
            return False

        try:
            top_leads = scrape_results.get("top_leads", [])
            rows_html = "\n".join(
                TOP_LEADS_ROW.format(
                    title=lead.get("title", "Unknown"),
                    company=lead.get("company", "Unknown"),
                    location=lead.get("location", "Unknown"),
                    score=int(lead.get("score", 0)),
                )
                for lead in top_leads
            )

            top_section = (
                TOP_LEADS_SECTION.format(rows=rows_html)
                if top_leads
                else ""
            )

            html_content = DIGEST_EMAIL_HTML.format(
                source_name=scrape_results.get("source_name", "Unknown Source"),
                platform=scrape_results.get("platform", "Unknown"),
                leads_found=scrape_results.get("leads_found", 0),
                high_priority=scrape_results.get("high_priority_count", 0),
                top_count=len(top_leads),
                top_leads_section=top_section,
                timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M"),
            )

            self._client.Emails.send({
                "from": self._from_address,
                "to": to_email,
                "subject": subject,
                "html": html_content,
            })

            logger.info("Digest email sent to %s: %s", to_email, subject)
            return True

        except Exception:
            logger.exception("Failed to send digest email to %s", to_email)
            return False


# ---------------------------------------------------------------------------
# Singleton
# ---------------------------------------------------------------------------
email_service = EmailService()
